import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

function generateSlug(name: string): string {
  return name
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-');
}

async function main() {
  console.log('🌱 Starting seed...');

  // Delete all existing skills first
  await prisma.skill.deleteMany({});
  console.log('🗑️ Existing skills deleted');

  // Seed new predefined skills (duplicates removed)
  const skills = [
    '3D Design and Augmented Reality (AR)',
    '3D Modeling',
    'A/B Testing and Experimentation',
    'Accounting',
    'Addiction Support',
    'Advanced Prototyping and Animation',
    'Aerospace Engineering',
    'Affiliate Marketing',
    'Agile Methodology',
    'Agricultural Science',
    'Animal Care',
    'Animation',
    'APIs and Integration',
    'Architecture',
    'Artificial Intelligence',
    'Art Instruction',
    'Astronomy',
    'Audio Editing',
    'Audit',
    'Auto Mechanics',
    'Back-end Development',
    'Baking',
    'Bicycle Repair',
    'Biology',
    'Biomedical Engineering',
    'Blockchain Development',
    'Blogging',
    'Board Management',
    'Bookkeeping',
    'Brand Management',
    'Brand Storytelling',
    'Budgeting',
    'Business Analysis',
    'Business Development',
    'Career Coaching',
    'Carpentry',
    'Change Management',
    'Chemical Engineering',
    'Chemistry',
    'Child Care',
    'Civil Engineering',
    'Cloud Computing',
    'Competitive Analysis',
    'Compliance Management',
    'Conflict Resolution',
    'Construction',
    'Content Marketing',
    'Content Writing',
    'Contract Negotiation',
    'Conversion Rate Optimization',
    'Cooking',
    'Copywriting',
    'Corporate Social Responsibility',
    'Counseling',
    'CPR',
    'Creative Writing',
    'Crisis Intervention',
    'Crisis Management',
    'Crowdfunding',
    'Cultural Sensitivity Training',
    'Curriculum Development',
    'Customer Relationship Management (CRM)',
    'Customer Service',
    'Cybersecurity',
    'Dance Instruction',
    'Data Analysis',
    'Data-Driven Design',
    'Data Visualization',
    'Dentistry',
    'Design Systems and Libraries',
    'DevOps',
    'Digital Marketing',
    'Disaster Response',
    'Diversity and Inclusion Training',
    'Donor Relations',
    'E-commerce Development',
    'Editing',
    'Elder Care',
    'E-learning Development',
    'Electrical Engineering',
    'Electrical Work',
    'Email Marketing',
    'Environmental Conservation',
    'Environmental Engineering',
    'Environmental Science',
    'Epidemiology',
    'Event Planning',
    'Fashion Design',
    'Financial Management',
    'First Aid',
    'Fitness Training',
    'Food Science',
    'Front-end Development',
    'Full-stack Development',
    'Fundraising',
    'Game Design',
    'Gardening',
    'Genetics',
    'Geology',
    'Grant Writing',
    'Graphic Design',
    'Grief Counseling',
    'Home Repair',
    'Human Resources Management',
    'Illustration',
    'Industrial Design',
    'Influencer Marketing',
    'Instructional Design',
    'Intellectual Property Management',
    'Interior Design',
    'Interpretation',
    'Investment Management',
    'Journalism',
    'Knitting',
    'Landscaping',
    'Leadership Development',
    'Legal Consulting',
    'Life Coaching',
    'Lobbying',
    'Logistics Management',
    'Logo Design',
    'Machine Learning',
    'Marine Biology',
    'Market Research',
    'Mechanical Engineering',
    'Mediation',
    'Mental Health Support',
    'Mentoring',
    'Meteorology',
    'Microbiology',
    'Mobile App Development',
    'Motivational Speaking',
    'Music Instruction',
    'Negotiation',
    'Network Administration',
    'Non-profit Management',
    'Nutrition Planning',
    'Nutrition Science',
    'Operations Management',
    'Optometry',
    'Painting',
    'Pay-Per-Click (PPC) Advertising',
    'Performance Management',
    'Pet Grooming',
    'Pharmacology',
    'Photo Editing',
    'Photography',
    'Physical Therapy',
    'Physics',
    'Plumbing',
    'Podcast Production',
    'Policy Development',
    'Presentation Skills',
    'Product Design',
    'Product Management',
    'Project Management',
    'Proofreading',
    'Proposal Writing',
    'Public Health',
    'Public Relations',
    'Public Speaking',
    'Quality Assurance',
    'Quality Management',
    'Recycling and Waste Management',
    'Renewable Energy Engineering',
    'Responsive and Adaptive Design',
    'Risk Management',
    'Sales',
    'Scriptwriting',
    'Scrum Master',
    'Search and Rescue',
    'Search Engine Marketing (SEM)',
    'Search Engine Optimization (SEO)',
    'Sewing',
    'Sign Language',
    'Social Entrepreneurship',
    'Social Media Management',
    'Software Testing',
    'Special Needs Support',
    'Speechwriting',
    'Sponsorship Acquisition',
    'Sports Coaching',
    'Storytelling',
    'Strategic Planning',
    'Suicide Prevention',
    'Supply Chain Management',
    'Sustainability Management',
    'Sustainable Design',
    'Talent Acquisition',
    'Tax Planning',
    'Teaching',
    'Team Building',
    'Technical Writing',
    'Training and Development',
    'Translation',
    'Tutoring',
    'UI Design',
    'Urban Planning',
    'User Research and Usability Testing',
    'UX Design',
    'Veterinary Medicine',
    'Video Editing',
    'Video Production',
    'Visual Storytelling',
    'Voice-over',
    'Voice User Interface (VUI) Design',
    'Volunteer Coordination',
    'Web Design',
    'Web Development',
    'Web Performance Optimization',
    'Wildlife Conservation',
    'Workshop Facilitation',
    'Yoga Instruction',
    // Additional suggestions
    'Accessibility Design',
    'Advocacy and Campaigning',
    'Community Organizing',
    'Data Privacy and Ethics',
    'Disaster Preparedness',
    'Financial Literacy Coaching',
    'Language Teaching',
    'Newsletter Writing',
    'Peer Support',
    'Podcasting Strategy',
  ].sort(); // Sort alphabetically for clean DB ordering

  for (const skill of skills) {
    const slug = generateSlug(skill);
    await prisma.skill.upsert({
      where: { slug },
      update: { name: skill, isActive: true },
      create: {
        name: skill,
        slug,
        source: 'PREDEFINED',
        isActive: true,
      },
    });
  }

  console.log(`✅ ${skills.length} skills seeded`);
  console.log('🎉 Seed complete!');
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
