import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import { Provider } from '@/components/ui/provider';
import './globals.css';

const poppins = Poppins({
  variable: '--font-poppins',
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light" style={{ colorScheme: 'light' }}>
      <body className={`${poppins.variable}`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
