/**
 * Default Open Graph image — used on the home page and any page that
 * doesn't define its own opengraph-image.tsx.
 *
 * Generated by Next.js at request time using next/og (Satori).
 * Output: 1200×630 PNG served at /opengraph-image.
 */

import { ImageResponse } from 'next/og';

export const runtime = 'edge';
export const alt = 'MasterGiver — Verified Business Reputation Profiles';
export const size = { width: 1200, height: 630 };
export const contentType = 'image/png';

export default function OgImage() {
  return new ImageResponse(
    (
      <div
        style={{
          width: '100%',
          height: '100%',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          background: 'linear-gradient(135deg, #2F2B77 0%, #4A45A0 100%)',
          padding: '80px',
        }}
      >
        {/* Badge */}
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            background: 'rgba(255,255,255,0.15)',
            borderRadius: '100px',
            padding: '8px 24px',
            marginBottom: '32px',
          }}
        >
          <span
            style={{
              color: 'rgba(255,255,255,0.9)',
              fontSize: '18px',
              fontWeight: 600,
              letterSpacing: '2px',
              textTransform: 'uppercase',
            }}
          >
            Verified Community Impact
          </span>
        </div>

        {/* Headline */}
        <div
          style={{
            color: '#FFFFFF',
            fontSize: '64px',
            fontWeight: 700,
            lineHeight: 1.1,
            textAlign: 'center',
            marginBottom: '24px',
            maxWidth: '900px',
          }}
        >
          MasterGiver
        </div>

        {/* Tagline */}
        <div
          style={{
            color: 'rgba(255,255,255,0.8)',
            fontSize: '28px',
            fontWeight: 400,
            textAlign: 'center',
            maxWidth: '800px',
            lineHeight: 1.4,
          }}
        >
          Turn your community impact into verified reputation signals that AI
          and search engines trust.
        </div>

        {/* Bottom domain */}
        <div
          style={{
            position: 'absolute',
            bottom: '48px',
            color: 'rgba(255,255,255,0.5)',
            fontSize: '20px',
          }}
        >
          mastergiver.com
        </div>
      </div>
    ),
    { ...size }
  );
}
